#include<opencv2/core/core.hpp>
#include<opencv2/highgui/highgui.hpp>
#include<opencv2/imgproc/imgproc.hpp>
#include <opencv2/objdetect.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/video.hpp>
#include <opencv2/videoio.hpp>
#include <opencv2/tracking.hpp>
#include <opencv2/opencv.hpp>
#include <opencv2/core/ocl.hpp>
#if _DEBUG 

#pragma comment(lib, "..\\lib\\debug\\opencv_calib3d330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_core330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_dnn330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_features2d330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_flann330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_highgui330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_imgcodecs330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_imgproc330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_ml330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_objdetect330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_photo330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_shape330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_stitching330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_superres330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_video330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_videoio330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_videostab330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_aruco330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_bgsegm330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_bioinspired330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_calib3d330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_ccalib330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_core330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_datasets330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_dnn330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_dpm330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_face330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_features2d330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_flann330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_fuzzy330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_highgui330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_imgcodecs330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_imgproc330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_line_descriptor330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_ml330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_objdetect330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_optflow330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_phase_unwrapping330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_photo330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_plot330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_reg330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_rgbd330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_saliency330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_shape330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_stereo330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_stitching330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_structured_light330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_superres330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_surface_matching330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_text330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_tracking330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_video330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_videoio330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_videostab330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_xfeatures2d330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_ximgproc330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_xobjdetect330d.lib")
#pragma comment(lib, "..\\lib\\debug\\opencv_xobjdetect330d.lib")

#else

#pragma comment(lib, "..\\lib\\release\\opencv_calib3d330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_core330.lib")
//#pragma comment(lib, "..\\lib\\release\\opencv_dnn330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_features2d330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_flann330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_highgui330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_imgcodecs330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_imgproc330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_ml330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_objdetect330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_photo330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_shape330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_stitching330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_superres330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_video330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_videoio330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_videostab330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_aruco330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_bgsegm330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_bioinspired330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_calib3d330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_ccalib330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_core330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_datasets330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_dnn330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_dpm330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_face330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_features2d330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_flann330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_fuzzy330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_highgui330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_imgcodecs330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_imgproc330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_line_descriptor330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_ml330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_objdetect330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_optflow330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_phase_unwrapping330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_photo330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_plot330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_reg330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_rgbd330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_saliency330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_shape330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_stereo330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_stitching330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_structured_light330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_superres330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_surface_matching330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_text330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_tracking330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_video330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_videoio330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_videostab330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_xfeatures2d330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_ximgproc330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_xobjdetect330.lib")
#pragma comment(lib, "..\\lib\\release\\opencv_xobjdetect330.lib")
#endif


using namespace std;
//using namespace cv;
